dist: trusty
sudo: required
services: docker

language: go

# This moves Kubernetes specific config files.
env:
  global:
  - CHANGE_MINIKUBE_NONE_USER=true
matrix:
  include:
  - name: "Whisk Action Tests"
    env: TESTS="system.basic.WskAction*"
  - name: "Whisk Basic Rest Tests"
    env: TESTS="system.basic.WskRest*"

before_install:
- sudo apt-get update -qq
- curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep

install:
# Make root mounted as rshared to fix kube-dns issues.
- sudo mount --make-rshared /
# Download kubeadm-dind-cluster script
- curl -Lo dind-cluster.sh https://cdn.rawgit.com/kubernetes-sigs/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.10.sh && chmod +x dind-cluster.sh && sudo mv dind-cluster.sh /usr/local/bin/
# Tell kubeadm-dind-cluster where to put kubectl
- export KUBECTL_DIR="${HOME}/.kubeadm-dind-cluster"
# Start Kubernetes
- ./test/bin/kubeadm-dind-start.sh
# Add Kubectl directory to the PATH.
- export PATH="${KUBECTL_DIR}:$PATH"
# Default to the newly created kubectl context
- kubectl config use-context dind
# Wait for Kubernetes to be up and ready.
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
# Fetch go deps
- dep ensure
# Install and configure knative
- ./test/bin/knative-install.sh

script:
- ./test/bin/integs.sh

after_failure:
- echo "************* FAILURE *************"
- cat kwsk.log
- dind-cluster.sh dump
